var json_INDEPENDENCIA_JUANGERMANROSCIOMunicipio_Capacho_Nuevo_Parroquia_Juan_German_Rosciojuan_german_roscio_centros_poblados_15 = {
"type": "FeatureCollection",
"name": "INDEPENDENCIA_JUANGERMANROSCIOMunicipio_Capacho_Nuevo_Parroquia_Juan_German_Rosciojuan_german_roscio_centros_poblados_15",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "pk": "1", "id": "1", "código": "201102", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "11", "municipio": "Capacho Nuevo", "capital_mu": "Capacho Nuevo", "código_par": "2", "parroquia": "Juan Germán Roscio", "capital_pa": "El Valle", "nombre": "La Cedrala", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.284198288902957, 7.783245394184515 ] ] } },
{ "type": "Feature", "properties": { "pk": "2", "id": "2", "código": "201102", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "11", "municipio": "Capacho Nuevo", "capital_mu": "Capacho Nuevo", "código_par": "2", "parroquia": "Juan Germán Roscio", "capital_pa": "El Valle", "nombre": "Los Guaudos", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.263974676904098, 7.793132314599055 ] ] } },
{ "type": "Feature", "properties": { "pk": "3", "id": "3", "código": "201102", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "11", "municipio": "Capacho Nuevo", "capital_mu": "Capacho Nuevo", "código_par": "2", "parroquia": "Juan Germán Roscio", "capital_pa": "El Valle", "nombre": "Tres Esquinas", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.275226575628935, 7.780558038568354 ] ] } },
{ "type": "Feature", "properties": { "pk": "4", "id": "4", "código": "201102", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "11", "municipio": "Capacho Nuevo", "capital_mu": "Capacho Nuevo", "código_par": "2", "parroquia": "Juan Germán Roscio", "capital_pa": "El Valle", "nombre": "Santa Rita", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.271163181316666, 7.775057202704751 ] ] } },
{ "type": "Feature", "properties": { "pk": "5", "id": "5", "código": "201102", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "11", "municipio": "Capacho Nuevo", "capital_mu": "Capacho Nuevo", "código_par": "2", "parroquia": "Juan Germán Roscio", "capital_pa": "El Valle", "nombre": "Santa Rita", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.284976752034154, 7.777751708480224 ] ] } },
{ "type": "Feature", "properties": { "pk": "6", "id": "6", "código": "201102", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "11", "municipio": "Capacho Nuevo", "capital_mu": "Capacho Nuevo", "código_par": "2", "parroquia": "Juan Germán Roscio", "capital_pa": "El Valle", "nombre": "EL VALLE", "descripció": "Capital Parroquia", "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.269085422182258, 7.780153744044088 ] ] } },
{ "type": "Feature", "properties": { "pk": "7", "id": "7", "código": "201102", "código_est": "20", "estado": "Táchira", "capital_es": "San Cristóbal", "código_mun": "11", "municipio": "Capacho Nuevo", "capital_mu": "Capacho Nuevo", "código_par": "2", "parroquia": "Juan Germán Roscio", "capital_pa": "El Valle", "nombre": "Mata de Guadua", "descripció": null, "fuente": "Digitalizado a partir de las Cartas 1:25000 y 1:100000 Cartografía Nacional. FUNDACITE UT TÁCHIRA SIGTA. Año 2017" }, "geometry": { "type": "MultiPoint", "coordinates": [ [ -72.265664293799333, 7.790862729659617 ] ] } }
]
}
